In [1]:
import pandas as pd

In [2]:
air_quality_no2 = pd.read_csv("data/air_quality_no2_long.csv", parse_dates=True)

In [4]:
air_quality_no2 = air_quality_no2[["date.utc", "location", "parameter", "value"]]

In [5]:
air_quality_no2.head()

                    date.utc location parameter  value
0  2019-06-21 00:00:00+00:00  FR04014       no2   20.0
1  2019-06-20 23:00:00+00:00  FR04014       no2   21.8
2  2019-06-20 22:00:00+00:00  FR04014       no2   26.5
3  2019-06-20 21:00:00+00:00  FR04014       no2   24.9
4  2019-06-20 20:00:00+00:00  FR04014       no2   21.4

In [6]:
air_quality_pm25 = pd.read_csv("data/air_quality_pm25_long.csv", parse_dates=True)

In [8]:
air_quality_no2 = air_quality_no2[["date.utc", "location", "parameter", "value"]]

In [9]:

air_quality_pm25.head()

,city,country,date.utc,location,parameter,value,unit
0,Antwerpen,BE,2019-06-18 06:00:00+00:00,BETR801,pm25,18.0,µg/m³
1,Antwerpen,BE,2019-06-17 08:00:00+00:00,BETR801,pm25,6.5,µg/m³
2,Antwerpen,BE,2019-06-17 07:00:00+00:00,BETR801,pm25,18.5,µg/m³
3,Antwerpen,BE,2019-06-17 06:00:00+00:00,BETR801,pm25,16.0,µg/m³
4,Antwerpen,BE,2019-06-17 05:00:00+00:00,BETR801,pm25,7.5,µg/m³

In [10]:
air_quality = pd.concat([air_quality_pm25, air_quality_no2], axis=0)

In [11]:
air_quality.head()

,city,country,date.utc,location,parameter,value,unit
0,Antwerpen,BE,2019-06-18 06:00:00+00:00,BETR801,pm25,18.0,µg/m³
1,Antwerpen,BE,2019-06-17 08:00:00+00:00,BETR801,pm25,6.5,µg/m³
2,Antwerpen,BE,2019-06-17 07:00:00+00:00,BETR801,pm25,18.5,µg/m³
3,Antwerpen,BE,2019-06-17 06:00:00+00:00,BETR801,pm25,16.0,µg/m³
4,Antwerpen,BE,2019-06-17 05:00:00+00:00,BETR801,pm25,7.5,µg/m³

In [12]:
print('Shape of the ``air_quality_pm25`` table: ', air_quality_pm25.shape)

Shape of the ``air_quality_pm25`` table:  (1110, 7)

In [13]:
print('Shape of the ``air_quality_no2`` table: ', air_quality_no2.shape)

Shape of the ``air_quality_no2`` table:  (2068, 4)

In [ ]:
print('Shape of the resulting ``air_quality`` table: ', air_quality.shape)

Shape of the resulting ``air_quality`` table:  (3178, 7)

In [18]:
air_quality = air_quality.drop(columns=["country", "unit"])

In [19]:
print('Shape of the resulting ``air_quality`` table: ', air_quality.shape)

Shape of the resulting ``air_quality`` table:  (3178, 5)

In [20]:
air_quality = air_quality.sort_values("date.utc")
air_quality.head()

,city,date.utc,location,parameter,value
2067,NaN,2019-05-07 01:00:00+00:00,London Westminster,no2,23.0
1003,NaN,2019-05-07 01:00:00+00:00,FR04014,no2,25.0
100,Antwerpen,2019-05-07 01:00:00+00:00,BETR801,pm25,12.5
1098,NaN,2019-05-07 01:00:00+00:00,BETR801,no2,50.5
1109,London,2019-05-07 01:00:00+00:00,London Westminster,pm25,8.0

In [21]:
stations_coord = pd.read_csv("data/air_quality_stations.csv")

In [22]:
stations_coord.head()

  location  coordinates.latitude  coordinates.longitude
0  BELAL01              51.23619                4.38522
1  BELHB23              51.17030                4.34100
2  BELLD01              51.10998                5.00486
3  BELLD02              51.12038                5.02155
4  BELR833              51.32766                4.36226

In [24]:
air_quality = air_quality.drop(columns=["city"])
air_quality.head()

                       date.utc            location parameter  value
2067  2019-05-07 01:00:00+00:00  London Westminster       no2   23.0
1003  2019-05-07 01:00:00+00:00             FR04014       no2   25.0
100   2019-05-07 01:00:00+00:00             BETR801      pm25   12.5
1098  2019-05-07 01:00:00+00:00             BETR801       no2   50.5
1109  2019-05-07 01:00:00+00:00  London Westminster      pm25    8.0

In [25]:
air_quality = pd.merge(air_quality, stations_coord, how="left", on="location")
air_quality.head()

,date.utc,location,parameter,value,coordinates.latitude,coordinates.longitude
0,2019-05-07 01:00:00+00:00,London Westminster,no2,23.0,51.49467,-0.13193
1,2019-05-07 01:00:00+00:00,FR04014,no2,25.0,48.83724,2.39390
2,2019-05-07 01:00:00+00:00,FR04014,no2,25.0,48.83722,2.39390
3,2019-05-07 01:00:00+00:00,BETR801,pm25,12.5,51.20966,4.43182
4,2019-05-07 01:00:00+00:00,BETR801,no2,50.5,51.20966,4.43182

In [28]:
air_quality_parameters = pd.read_csv("data/air_quality_parameters.csv")
air_quality_parameters.head()

     id                                        description  name
0    bc                                       Black Carbon    BC
1    co                                    Carbon Monoxide    CO
2   no2                                   Nitrogen Dioxide   NO2
3    o3                                              Ozone    O3
4  pm10  Particulate matter less than 10 micrometers in...  PM10

In [29]:
air_quality = pd.merge(air_quality, air_quality_parameters, how='left', left_on='parameter', right_on='id')
air_quality.head()

,date.utc,location,parameter,value,coordinates.latitude,coordinates.longitude,id,description,name
0,2019-05-07 01:00:00+00:00,London Westminster,no2,23.0,51.49467,-0.13193,no2,Nitrogen Dioxide,NO2
1,2019-05-07 01:00:00+00:00,FR04014,no2,25.0,48.83724,2.39390,no2,Nitrogen Dioxide,NO2
2,2019-05-07 01:00:00+00:00,FR04014,no2,25.0,48.83722,2.39390,no2,Nitrogen Dioxide,NO2
3,2019-05-07 01:00:00+00:00,BETR801,pm25,12.5,51.20966,4.43182,pm25,Particulate matter less than 2.5 micrometers i...,PM2.5
4,2019-05-07 01:00:00+00:00,BETR801,no2,50.5,51.20966,4.43182,no2,Nitrogen Dioxide,NO2

In [30]:
passengers = pd.DataFrame({
    "passenger_id": [1, 2, 3, 4],
    "name": ["Alice", "Bob", "Charlie", "Dana"],
    "class_id": [1, 3, 2, 1]
})

classes = pd.DataFrame({
    "class_id": [1, 2, 3],
    "class_name": ["First", "Second", "Third"],
    "deck": ["A", "C", "E"]
})

print(passengers)
print(classes)

   passenger_id     name  class_id
0             1    Alice         1
1             2      Bob         3
2             3  Charlie         2
3             4     Dana         1
   class_id class_name deck
0         1      First    A
1         2     Second    C
2         3      Third    E

In [31]:
merged = passengers.merge(classes, on="class_id")
merged

   passenger_id     name  class_id class_name deck
0             1    Alice         1      First    A
1             2      Bob         3      Third    E
2             3  Charlie         2     Second    C
3             4     Dana         1      First    A

In [ ]:
passengers2 = pd.DataFrame({
    "passenger_id": [1, 2, 5],
    "name": ["Alice", "Bob", "Eve"],
    "class_id": [1, 3, 9]
})

passengers2.merge(classes, on="class_id")

   passenger_id   name  class_id class_name deck
0             1  Alice         1      First    A
1             2    Bob         3      Third    E

In [33]:
passengers2.merge(classes, on="class_id", how="left")

   passenger_id   name  class_id class_name deck
0             1  Alice         1      First    A
1             2    Bob         3      Third    E
2             5    Eve         9        NaN  NaN