In [2]:
import yfinance as yf

/Users/antonipankowski/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [3]:
data = yf.download("AAPL", start="2024-01-01", end="2024-12-31")
data.head()

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open    Volume
Ticker            AAPL        AAPL        AAPL        AAPL      AAPL
Date
2024-01-02  183.562195  186.330858  181.831782  185.055288  82488700
2024-01-03  182.187775  183.799536  181.376945  182.158112  58414500
2024-01-04  179.873932  181.040717  178.855462  180.111236  71983600
2024-01-05  179.152130  180.714448  178.153440  179.953077  62379700
2024-01-08  183.483078  183.522639  179.468523  180.051916  59144500

In [4]:
data = yf.download(["AAPL", "TSLA", "SPY"], start="2024-01-01", end="2024-12-31")
data.head()

[*********************100%***********************]  3 of 3 completed

Price            Close                                High              \
Ticker            AAPL         SPY        TSLA        AAPL         SPY
Date
2024-01-02  183.562195  459.991180  248.419998  186.330858  460.983881
2024-01-03  182.187775  456.234558  238.449997  183.799536  458.570274
2024-01-04  179.873932  454.765015  237.929993  181.040717  458.346447
2024-01-05  179.152130  455.387939  237.490005  180.714448  457.840437
2024-01-08  183.483078  461.889038  240.449997  183.522639  462.035015

Price                          Low                                Open  \
Ticker            TSLA        AAPL         SPY        TSLA        AAPL
Date
2024-01-02  251.250000  181.831782  457.889027  244.410004  185.055288
2024-01-03  245.679993  181.376945  455.631168  236.320007  182.158112
2024-01-04  242.699997  178.855462  454.541164  237.729996  180.111236
2024-01-05  240.119995  178.153440  453.937825  234.899994  179.953077
2024-01-08  241.250000  179.468523  455.757750  235.300003  180.051916

Price                                 Volume
Ticker             SPY        TSLA      AAPL        SPY       TSLA
Date
2024-01-02  459.514313  250.080002  82488700  123623700  104654200
2024-01-03  457.830619  244.979996  58414500  103585900  121082600
2024-01-04  455.757686  239.250000  71983600   84232200  102629300
2024-01-05  454.969433  236.860001  62379700   86118900   92488900
2024-01-08  455.884273  236.139999  59144500   74879100   85166600

In [5]:
data.shape

(251, 15)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 251 entries, 2024-01-02 to 2024-12-30
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   (Close, AAPL)   251 non-null    float64
 1   (Close, SPY)    251 non-null    float64
 2   (Close, TSLA)   251 non-null    float64
 3   (High, AAPL)    251 non-null    float64
 4   (High, SPY)     251 non-null    float64
 5   (High, TSLA)    251 non-null    float64
 6   (Low, AAPL)     251 non-null    float64
 7   (Low, SPY)      251 non-null    float64
 8   (Low, TSLA)     251 non-null    float64
 9   (Open, AAPL)    251 non-null    float64
 10  (Open, SPY)     251 non-null    float64
 11  (Open, TSLA)    251 non-null    float64
 12  (Volume, AAPL)  251 non-null    int64
 13  (Volume, SPY)   251 non-null    int64
 14  (Volume, TSLA)  251 non-null    int64
dtypes: float64(12), int64(3)
memory usage: 31.4 KB

In [7]:
data.isnull().sum()

Price   Ticker
Close   AAPL      0
        SPY       0
        TSLA      0
High    AAPL      0
        SPY       0
        TSLA      0
Low     AAPL      0
        SPY       0
        TSLA      0
Open    AAPL      0
        SPY       0
        TSLA      0
Volume  AAPL      0
        SPY       0
        TSLA      0
dtype: int64

In [8]:
import pandas as pd

In [9]:
pd.set_option("display.float_format", "{:.2f}".format)

In [10]:
data.head()

Price       Close                 High                  Low                \
Ticker       AAPL    SPY   TSLA   AAPL    SPY   TSLA   AAPL    SPY   TSLA
Date
2024-01-02 183.56 459.99 248.42 186.33 460.98 251.25 181.83 457.89 244.41
2024-01-03 182.19 456.23 238.45 183.80 458.57 245.68 181.38 455.63 236.32
2024-01-04 179.87 454.77 237.93 181.04 458.35 242.70 178.86 454.54 237.73
2024-01-05 179.15 455.39 237.49 180.71 457.84 240.12 178.15 453.94 234.90
2024-01-08 183.48 461.89 240.45 183.52 462.04 241.25 179.47 455.76 235.30

Price        Open                  Volume
Ticker       AAPL    SPY   TSLA      AAPL        SPY       TSLA
Date
2024-01-02 185.06 459.51 250.08  82488700  123623700  104654200
2024-01-03 182.16 457.83 244.98  58414500  103585900  121082600
2024-01-04 180.11 455.76 239.25  71983600   84232200  102629300
2024-01-05 179.95 454.97 236.86  62379700   86118900   92488900
2024-01-08 180.05 455.88 236.14  59144500   74879100   85166600

In [11]:
data.to_csv("data/market_data.csv")